// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsefzwmcykddpeczlqca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzZWZ6d21jeWtkZHBlY3pscWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTI4NjMsImV4cCI6MjA3MzI2ODg2M30.I8RPJcVbUt8cjhFlbFFUXigM2OS9aL6Yusi6FBDfb9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});